version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: financetracker-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=financetracker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d FinanceTrackerDb"]
      interval: 10s
      timeout: 5s
      retries: 5
        
  
  api:
    container_name: financetracker-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8081;http://+:8080
      - Jwt__Key=${API_KEY}
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=FinanceTrackerDb;Username=postgres;Password=${POSTGRES_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
      
volumes:
  postgres_data:
